---
name: CI

on:
  push:
  pull_request:
    types:
      - closed

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml

  bump:
    name: Bump
    needs: tests
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/bump.yaml
